### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by sblondon** [rreha/luatoolbox#1]
`readme.md` file states luatoolbox as 'a better, open source replacement'. However there is no licence file in the repository. So the source code is available but it's not open source.

Can you add a file of a FOSS licence?

**Comment by rreha** [comment]
hey, didn't really know that somebody really cared about this homebrew... i've just added an MIT License now. use it however you want i don't really mind it 👍

**Comment by sblondon** [comment]
I searched for FOSS source code for PSP tester then I found your repository ;)
